[project]
authors = ["Emmanuelle Sarrazin <emmanuelle.sarrazin@cnes.fr>"]
channels = ["conda-forge"]
description = "Cookbook for manage large datasets"
name = "large-dataset-cookbook"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
pip = ">=25.0,<26"
numpy = ">=2.2.2,<3"
pandas = ">=2.2.3,<3"
jupyterlab = ">=4.3.5,<5"
matplotlib = ">=3.10.0,<4"
pyarrow = ">=19.0.0,<20"

[pypi-dependencies]
memory-profiler = ">=0.61.0, <0.62"
